version: '3.1'
  
services:
  drupal-7:
    build:
      context: ./docker/
      args:
        BRANCH: "7.x-1.x"
    ports:
     - "7007:443"
    volumes:
      - /var/www/html/sites/all/modules
      - /var/www/html/profiles
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - /var/www/html/sites/all/themes
  drupal-7-db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_PORT: 3306
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

